{
  viewer {
    homes {
      consumption(resolution: HOURLY, last: 100) {
        nodes {
          from
          to
          cost
          unitPrice
          unitPriceVAT
          consumption
          consumptionUnit
        }
      }
    }
  }
}

